### ISSUE TITLE
observer is prerequisite for etop 

### ISSUE THREAD

**Issue by ghost** [TI-Tokyo/Riak-Package-Builders-Vagrant#1]
FYI - You may want to check this, because on my builds it's bitten me, but if erlang is built without observer (which requires wx) - etop fails to run.

**Comment by Bob-The-Marauder** [comment]
Pretty sure that `riak top` will run on these builds. Not sure if `etop` adds any functionality that `riak top` misses.

**Comment by ghost** [comment]
I think `riak top` is just a wrapper for etop

**Comment by llelf** [comment]
`etop` is part of `observer`

**Comment by Bob-The-Marauder** [comment]
Is there any need for `etop`, especially as `riak top` works as is? If you install the old Basho packages, they needed very few dependencies and that is the same with these builds. However, if I build a package with WX included i.e. `etop` friendly, suddenly the number of dependencies you need to install on a clean machine increases significantly. Having previously had uses complain of package bloat with the WX builds, is there any need for this?

**Comment by ghost** [comment]
That's a question for the community - I've not been happy with the package bloat but then had people complaining that riak top wouldn't run - tracked it down to my ommision of observer. I suppose I've used 'riak top' a lot in order to find buggy gen_servers using lots of CPU but whether that's something that users would be expected to do is an open question. Certainly including WX bloats the runtime dependency hugely.

**Comment by llelf** [comment]
> suddenly the number of dependencies you need to install on a clean machine increases significantly

You mean OS-package-manager dependencies?  Or what?
Because I'm pretty sure wx-the-package is not required.

**Comment by ghost** [comment]
OS-package-manager dependencies

**Comment by llelf** [comment]
They are not needed.

```
configure:5036: checking for standard build of wxWidgets
configure:5069: checking for wx-config
configure:5101: result: no
```

but
```
3> etop:start([{output,text}]).      % ≡ riak top

========================================================================================
 nonode@nohost                                                             08:17:55
 Load:  cpu         0               Memory:  total       14371    binary         15
        procs      27                        processes    4076    code         4993
        runq        0                        atom          258    ets           227

Pid            Name or Initial Func    Time    Reds  Memory    MsgQ Current Function
----------------------------------------------------------------------------------------
<0.3.0>        erl_prim_loader          '-'  246503  163264       0 erl_prim_loader:loop
<0.19.0>       code_server              '-'   86895   67752       0 code_server:loop/1  
<0.18.0>       file_server_2            '-'   13875   24528       0 gen_server:loop/6   
<0.7.0>        application_controll     '-'    4240  263832       0 gen_server:loop/6   
<0.23.0>       user_drv                 '-'    4237   16664       0 user_drv:server_loop
<0.0.0>        init                     '-'    3164   18432       0 init:loop/1         
<0.26.0>       erlang:apply/2           '-'    2841  230344       0 shell:shell_rep/4   
<0.25.0>       group:server/3           '-'    2029    8720       0 group:server_loop/3 
<0.11.0>       kernel_sup               '-'    1442    9080       0 gen_server:loop/6   
<0.6.0>        error_logger             '-'    1048   34304       0 gen_event:fetch_msg/
========================================================================================
```

**Comment by ghost** [comment]
@llelf - ok lets close this out - thanks for checking .
